- hosts: localhost
  gather_facts: no
  vars_files:
  - aws_cred.yml
  tasks:
  - name: "Installing Boto3 library"
    pip:
      name: boto
      state: present
  - name: "Security Group for both Master and Worker Nodes"
    ec2_group:
      name: MultiNodeCluster
      description: "This SG allows allows all traffic"
      region: ap-south-1
      aws_access_key: "{{ access_key }}"
      aws_secret_key: "{{ secret_key }}"
      rules:
      - proto: all
        cidr_ip: 0.0.0.0/0
      rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
  - name: "Launching Master Node"
    ec2:
      key_name: ansiblekey
      instance_type: t2.micro
      image: ami-0eeb03e72075b9bcc
      wait: true
      group: MultiNodeCluster
      count: 1
      vpc_subnet_id: subnet-0ecad70c1783cb8f6
      assign_public_ip: yes
      region: ap-south-1
      state: present
      aws_access_key: "{{ access_key }}"
      aws_secret_key: "{{ secret_key }}"
      instance_tags:
        Name: MasterNode
    register: master_info
  - name: "Add MasterNode to host group"
    add_host:
      hostname: "{{ item.public_ip }}"
      groupname: master
    loop: "{{ master_info['instances'] }}"
  - name: "Waiting for SSH"
    wait_for:
      host: "{{ item.public_dns_name }}"
      port: 22
      state: started
    loop: "{{ master_info['instances'] }}"

- hosts: master
  roles:
  - MasterNode



  
