apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: wpos
  name: wpos
spec:
  containers:
  - image: wordpress:5.1.1-php7.3-apache
    name: wpos
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
